import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          FollowHeader(),
        ]),
      ),
    );
  }
}

class FollowHeader extends StatelessWidget {
  final String firstBackgroundImage = 'assets/images/follow_header_bg.png';
  final String otherBackgroundImage = 'assets/images/follow_header_bg.jpg';

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0), // 添加一些内边距
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly, // 均匀分布各个项目
            children: List.generate(5, (index) {
              final titles = ['题本名称', '选择专业', '题型数量', '选择难度', '生成套数'];
              return _buildItem(context, '${index + 1}', titles[index]);
            }),
          ),
        ),
      ],
    );
  }

  Widget _buildItem(BuildContext context, String number, String title) {
    return Expanded(
      child: Container(
        height: 60, // 根据需要调整高度
        decoration: BoxDecoration(
          image: DecorationImage(
            image: number == "1" ? AssetImage(firstBackgroundImage) : AssetImage(otherBackgroundImage),
            fit: BoxFit.fitWidth, // 确保背景图完全覆盖容器
          ),
          borderRadius: BorderRadius.circular(8.0), // 圆角半径，根据需要调整
        ),
        child: Center(
          child: Text(
            "$number.$title",
            textAlign: TextAlign.center,
            style: TextStyle(
              color: Colors.black87, // 确保文字颜色与背景对比度高
              fontSize: 16,
              fontFamily: 'PingFang SC',
              fontWeight: FontWeight.w400,
            ),
          ),
        ),
      ),
    );
  }
}